#!/usr/bin/env bash
# Displays the contents of the file 'etc/passwd'
#  only display the username, usr id, and user home directory path.

while read -r passwd; do
 echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
